### ISSUE TITLE
Options for controlling the game. 

### ISSUE THREAD

**Issue by Kabyss** [Tr-Jono/on9wordchainbot#1]
Much needed feature is to add a check when the game can be played in a group and restrict to x number of games in y number of hours/days etc. Often members play the game for a long time in groups resulting in flooding. If not possible to implement in the official bot, please give some hints on how it can be done.

**Comment by jonowo** [comment]
You can create a fork of the bot and add the check [here](https://github.com/jonowo/on9wordchainbot/blob/master/on9wordchainbot/handlers/gameplay.py#L43). Make a SQL query to count the number of games played in the last y hours and return if it exceeds your limit.

**Comment by Kabyss** [comment]
thank you.
